<a href="https://colab.research.google.com/github/AbdillahHalim/Customer-personality-data-Clustering-Classification/blob/main/%5BKlasifikasi%5D_Submission_Akhir_BMLP_Abdillah_Halim_Hanafi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. Import Library**

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import warnings
warnings.filterwarnings("ignore")

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay, accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from imblearn.over_sampling import SMOTE

# **2. Memuat Dataset dari Hasil Clustering**

In [12]:
# import dataset
df = pd.read_csv("/content/3clusterData (2).csv")

In [13]:
# menampilkan data
df.head()

Income  spending  totalTransaction  incomeCategory  Cluster KM
0  129.664953        50                 5             0.0           0
1  253.359428       825                21             2.0           1
2  268.270386      1086                16             2.0           1
3  170.842032        34                 4             0.0           0
4   66.543219       359                25             0.0           0

# **3. Data Splitting**

In [14]:
# membagi dataset menjadi dua bagian fitur (X) dan label (y)
X = df.drop(['Cluster KM'], axis=1)
y = df['Cluster KM']

In [15]:
# membagi dataset menjadi 0.75 - 0.25, dan 0.25 merupakan data uji
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

# **4. Membangun Model Klasifikasi**


## **a. Membangun Model Klasifikasi**

Setelah memilih algoritma klasifikasi yang sesuai, langkah selanjutnya adalah melatih model menggunakan data latih.

Berikut adalah rekomendasi tahapannya.
1. Pilih algoritma klasifikasi yang sesuai, seperti Logistic Regression, Decision Tree, Random Forest, atau K-Nearest Neighbors (KNN).
2. Latih model menggunakan data latih.

In [16]:
# inisiasi model
model1 = KNeighborsClassifier()

# fit model ke data train yang dibagi sebelumnya
model1.fit(X_train, y_train)

KNeighborsClassifier()

In [17]:
# inisiasi model
model2 = RandomForestClassifier()

# fit model ke data train yang dibagi sebelumnya
model2.fit(X_train, y_train)

RandomForestClassifier()

## **b. Evaluasi Model Klasifikasi**

Berikut adalah **rekomendasi** tahapannya.
1. Lakukan prediksi menggunakan data uji.
2. Hitung metrik evaluasi seperti Accuracy dan F1-Score (Opsional: Precision dan Recall).
3. Buat confusion matrix untuk melihat detail prediksi benar dan salah.

In [18]:
def evaluate(model, X_train, X_test, y_train, y_test):
    """
    Fungsi ini membuat evaluasi kinerja model klasifikasi

    Argumen:
    - model: Objek model yang akan dievaluasi.
    - X_train: Data latih fitur.
    - X_test: Data uji fitur.
    - y_train: Label data latih.
    - y_test: Label data uji.

    Pengembalian:
    Tidak ada

    Tampilan:
    - Hasil evaluasi data latih dan data uji.
    - Hasil confusion matrix dan metrik evaluasi.
    """

    y_test_pred = model.predict(X_test)
    y_train_pred = model.predict(X_train)

    print("HASIL TRAINING : \n=================================================================================")
    clf_report = pd.DataFrame(classification_report(y_train, y_train_pred, output_dict=True))
    print(f"CONFUSION MATRIX:\n{confusion_matrix(y_train, y_train_pred)}")
    print(f"ACCURACY SCORE:\n{accuracy_score(y_train, y_train_pred):.4f}")
    print(f"CLASSIFICATION REPORT:\n{clf_report}")
    print("=================================================================================")

    print("TESTING RESULTS: \n=================================================================================")
    clf_report = pd.DataFrame(classification_report(y_test, y_test_pred, output_dict=True))
    print(f"CONFUSION MATRIX:\n{confusion_matrix(y_test, y_test_pred)}")
    print(f"ACCURACY SCORE:\n{accuracy_score(y_test, y_test_pred):.4f}")
    print(f"CLASSIFICATION REPORT:\n{clf_report}")
    print("=================================================================================")

In [19]:
evaluate(model1, X_train, X_test, y_train, y_test)

HASIL TRAINING : 
CONFUSION MATRIX:
[[1611    1]
 [   0  771]]
ACCURACY SCORE:
0.9996
CLASSIFICATION REPORT:
                    0           1  accuracy    macro avg  weighted avg
precision     1.00000    0.998705   0.99958     0.999352      0.999581
recall        0.99938    1.000000   0.99958     0.999690      0.999580
f1-score      0.99969    0.999352   0.99958     0.999521      0.999580
support    1612.00000  771.000000   0.99958  2383.000000   2383.000000
TESTING RESULTS: 
CONFUSION MATRIX:
[[565   2]
 [  0 228]]
ACCURACY SCORE:
0.9975
CLASSIFICATION REPORT:
                    0           1  accuracy   macro avg  weighted avg
precision    1.000000    0.991304  0.997484    0.995652      0.997506
recall       0.996473    1.000000  0.997484    0.998236      0.997484
f1-score     0.998233    0.995633  0.997484    0.996933      0.997488
support    567.000000  228.000000  0.997484  795.000000    795.000000


In [20]:
evaluate(model2, X_train, X_test, y_train, y_test)

HASIL TRAINING : 
CONFUSION MATRIX:
[[1612    0]
 [   0  771]]
ACCURACY SCORE:
1.0000
CLASSIFICATION REPORT:
                0      1  accuracy  macro avg  weighted avg
precision     1.0    1.0       1.0        1.0           1.0
recall        1.0    1.0       1.0        1.0           1.0
f1-score      1.0    1.0       1.0        1.0           1.0
support    1612.0  771.0       1.0     2383.0        2383.0
TESTING RESULTS: 
CONFUSION MATRIX:
[[567   0]
 [  0 228]]
ACCURACY SCORE:
1.0000
CLASSIFICATION REPORT:
               0      1  accuracy  macro avg  weighted avg
precision    1.0    1.0       1.0        1.0           1.0
recall       1.0    1.0       1.0        1.0           1.0
f1-score     1.0    1.0       1.0        1.0           1.0
support    567.0  228.0       1.0      795.0         795.0


## **e. Analisis Hasil Evaluasi Model Klasifikasi**

**Analisa Hasil :** Model terbaik memiliki nilai akurasi dan F1-score 1,berdasarkan hasil yang ditampilkan,  model memiliki kinerja yang sangat baik, baik pada tahap training maupun testing.

**Rekomendasi :** Uji dengan data baru untuk memastikan model tidak mengalami overfitting, uji model dengan data yang benar-benar baru dan belum pernah digunakan dalam proses training maupun testing.